name: Lora CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    env:
      MIX_ENV: test
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18.2" # [Required] Define the Elixir version
          otp-version: "27.2.1" # [Required] Define the Erlang/OTP version
      
      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
        
      - name: Run formatter check
        run: mix format --check-formatted
        
      - name: Compile (with warnings as errors)
        run: mix compile --warnings-as-errors
        
      - name: Run Dialyzer
        run: mix dialyzer
        
      - name: Run tests
        run: mix test --cover --export-coverage default
        
      - name: Run test coverage
        run: mix test.coverage
        
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cover/
          
  build:
    name: Build Release
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    env:
      MIX_ENV: prod
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.0'
          otp-version: '26.0'
          
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
          
      - name: Install dependencies
        run: mix deps.get --only prod
        
      - name: Compile assets
        run: |
          cd apps/lora_web/assets
          npm ci
          npm run deploy
          
      - name: Compile and build release
        run: mix do compile, release
        
      - name: Upload release
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: _build/prod/rel/lora/
